server=127.0.0.1:5354
logs_enabled=true
ttl=24h
direct_dns={
    1.1.1.1,
    8.8.8.8,
}
fallback_dns=8.8.8.8:53
domains_file=/etc/ipscoutdns/domains.txt
reachable_hosts=/tmp/ipscoutdns/reachable.hosts
reachable_domains_file=/tmp/ipscoutdns/reachable.domains
reachable_ips_file=/tmp/ipscoutdns/reachable.ips
unreachable_domains_file=/tmp/ipscoutdns/unreachable.domains
unreachable_ips_file=/tmp/ipscoutdns/unreachable.ips
dns_timeout=3s
tcp_timeout=3s
tcp_port=443
tcp_route=direct
parallel_tests=16
answer_ttl=300
